# Generated by Django 6.0.4 on 2026-04-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSEnvironment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='环境名称')),
                ('access_key_id', models.CharField(max_length=200, verbose_name='Access Key ID')),
                ('secret_access_key', models.CharField(max_length=200, verbose_name='Secret Access Key')),
                ('region', models.CharField(max_length=50, verbose_name='区域')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认环境')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AWS环境凭证',
                'verbose_name_plural': 'AWS环境凭证',
                'db_table': 'aws_environments',
                'ordering': ['-created_at'],
            },
        ),
    ]
