# Generated by Django 6.0.4 on 2026-04-28 07:04

import aws.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevOpsIncident',
            fields=[
                ('id', models.CharField(default=aws.models.generate_incident_id, max_length=100, primary_key=True, serialize=False)),
                ('incident_id', models.CharField(max_length=100, unique=True, verbose_name='事件ID')),
                ('title', models.CharField(max_length=255, verbose_name='调查标题')),
                ('status', models.CharField(choices=[('investigating', '调查中'), ('completed', '已完成'), ('closed', '已关闭'), ('cancelled', '已取消'), ('failed', '失败')], default='investigating', max_length=20, verbose_name='状态')),
                ('severity', models.CharField(choices=[('critical', '严重'), ('high', '高'), ('medium', '中'), ('low', '低')], default='high', max_length=20, verbose_name='严重程度')),
                ('environment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='环境ID')),
                ('environment_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='环境名称')),
                ('background', models.TextField(verbose_name='事件背景')),
                ('description', models.TextField(verbose_name='事件说明')),
                ('progress', models.JSONField(default=dict, verbose_name='调查进度')),
                ('timeline', models.JSONField(default=list, verbose_name='推理时间线')),
                ('root_cause', models.JSONField(default=dict, verbose_name='根因分析')),
                ('fix_suggestions', models.JSONField(default=dict, verbose_name='修复建议')),
                ('chat_messages', models.JSONField(default=list, verbose_name='对话消息')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devops_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DevOps事件调查',
                'verbose_name_plural': 'DevOps事件调查',
                'db_table': 'devops_incidents',
                'ordering': ['-created_at'],
            },
        ),
    ]
