# Generated by Django 6.0.4 on 2026-04-24 03:46

import django.db.models.deletion
import workflow.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.CharField(default=workflow.models.generate_workflow_id, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('template_id', models.CharField(blank=True, max_length=100, null=True)),
                ('steps', models.JSONField(default=list)),
                ('variables', models.JSONField(default=dict)),
                ('triggers', models.JSONField(default=list)),
                ('settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.CharField(default=workflow.models.generate_execution_id, max_length=100, primary_key=True, serialize=False)),
                ('workflow_id_str', models.CharField(max_length=100)),
                ('workflow_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('idle', '空闲'), ('running', '执行中'), ('paused', '已暂停'), ('completed', '已完成'), ('failed', '执行失败'), ('cancelled', '已取消')], default='idle', max_length=20)),
                ('variables', models.JSONField(default=dict)),
                ('step_results', models.JSONField(default=dict)),
                ('step_statuses', models.JSONField(default=dict)),
                ('logs', models.JSONField(default=list)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflow.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
